# Generated by Django 4.0.3 on 2022-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipolimeros', '0003_alter_mantenimientopmultip_codigopostalf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientoclientes',
            name='Constancia',
            field=models.FileField(null=True, upload_to='constanciasFiscales/'),
        ),
    ]
