# Generated by Django 4.0.3 on 2022-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospectos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre de Prospecto')),
            ],
            options={
                'verbose_name': 'Categoría de Prospecto',
                'verbose_name_plural': 'Categorías de Prospecto',
                'ordering': ['id'],
            },
        ),
    ]
