# Generated by Django 4.0.3 on 2022-05-02 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enigmaVentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoProspectos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('RazonSocial', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('Rfc', models.CharField(max_length=50, verbose_name='RFC')),
                ('NombreComercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('CodRuta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo de Ruta')),
                ('CodAgente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo de Agente')),
                ('NombreAgente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de Agente')),
                ('ContactoProspecto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto de Prospecto')),
                ('DireccionFiscal', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección Fiscal')),
                ('NumExt', models.CharField(blank=True, max_length=6, verbose_name='Numero Exterior')),
                ('NumInt', models.CharField(blank=True, max_length=6, verbose_name='Numero Interior')),
                ('Colonia', models.CharField(blank=True, max_length=200, verbose_name='Colonia')),
                ('Estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('Municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('CodigoPostal', models.IntegerField(blank=True, null=True, verbose_name='Código Postal')),
                ('DireccionVenta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección Punto de Venta')),
                ('CorreoElectronico', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('Telefono', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Numero Telefonico')),
                ('TelefonoCelular', models.PositiveBigIntegerField(verbose_name='Numero Celular')),
                ('ListaPrecios', models.CharField(blank=True, choices=[('LPA', 'LPA'), ('LPD', 'LPD')], max_length=250, null=True, verbose_name='Lista de Precios')),
                ('DescuentoGeneral', models.SmallIntegerField(blank=True, null=True, verbose_name='Descuento General (%)')),
                ('Plazo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Plazo')),
                ('VolumenCompra', models.CharField(blank=True, max_length=250, null=True, verbose_name='Volumen de Compra')),
                ('Propietario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Propietario')),
                ('Gerente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gerente')),
                ('PersonaCompras', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona Encargada de Compras')),
                ('PersonaVentas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona Encargada de Ventas')),
                ('ProductosInteres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Productos o Marcas en Los Que Esta Interesado')),
                ('MarcaPrincipal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marca Principal')),
                ('PorcentajeMarcaPrincipal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentaje de marca principal')),
                ('SegundaMarca', models.CharField(blank=True, max_length=200, null=True, verbose_name='Segunda Marca')),
                ('PorcentajeSegundaMarca', models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentaje de segunda marca')),
                ('Otro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro')),
                ('PorcentajeOtro', models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentaje de otra marca')),
                ('Decorativo', models.IntegerField(blank=True, null=True, verbose_name='Decorativo (%)')),
                ('Automotriz', models.IntegerField(blank=True, null=True, verbose_name='Automotriz (%)')),
                ('Funcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Funcion o Puesto Dueño')),
                ('NivelInventario', models.IntegerField(blank=True, null=True, verbose_name='Nivel de Inventario aproximado ($)')),
                ('VentasMensuales', models.IntegerField(blank=True, null=True, verbose_name='Ventas Mensuales Aproximadas ($)')),
                ('TamanoPuntoVenta', models.IntegerField(blank=True, null=True, verbose_name='Tamaño de punto de venta (m2)')),
                ('MarcaRotulacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca de Rotulación')),
                ('NumeroCortinas', models.IntegerField(blank=True, null=True, verbose_name='Numero de Cortinas')),
                ('NumeroEmpleados', models.IntegerField(blank=True, null=True, verbose_name='Numero de Empleados')),
                ('Vialidad', models.CharField(blank=True, choices=[('Avenida Principal', 'Avenida Principal'), ('Avenida Secundaria', 'Avenida Secundaria'), ('Calle', 'Calle'), ('Plaza Comercial', 'Plaza Comercial')], max_length=100, verbose_name='Vialidad')),
                ('Observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('TipoProspecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigmaVentas.prospectos')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioPromexProspecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento de Prospecto',
                'verbose_name_plural': 'Mantenimiento de Prospectos',
                'ordering': ['-id'],
            },
        ),
    ]
