# Generated by Django 4.0.3 on 2022-05-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaVentas', '0004_solicitudcredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentos', models.CharField(choices=[('RFC Empresa', 'RFC Empresa'), ('Identificación Oficial REP Legal', 'Identificación Oficial REP Legal'), ('Comp. Domicilio Empresa', 'Comp. Domicilio Empresa'), ('Comp. Domicilio REP Legal', 'Comp. Domicilio REP Legal'), ('Acta Constitutiva', 'Acta Constitutiva'), ('Pagaré con Aval', 'Pagaré con Aval'), ('Identificación Oficial Aval', 'Identificación Oficial Aval'), ('Comp. Domicilio Aval', 'Comp. Domicilio Aval'), ('Estados de Cuenta Recientes(3)', 'Estados de Cuenta Recientes(3)'), ('Estados Financieros Anual y Mensual', 'Estados Financieros Anual y Mensual')], max_length=200)),
            ],
        ),
    ]
