# Generated by Django 4.0.3 on 2022-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaVentas', '0005_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='DocumentosEntregados',
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='DocumentosEntregados',
            field=models.ManyToManyField(to='enigmaVentas.documentos'),
        ),
    ]
