# Generated by Django 4.0.3 on 2022-05-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaVentas', '0007_mantenimientoclientes_telefono2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codLinea', models.CharField(blank=True, max_length=200, verbose_name='Codigo de Linea')),
                ('codColor', models.CharField(blank=True, max_length=200, verbose_name='Codigo de Color')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='LPA')),
                ('lpd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='LPD')),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['-id'],
            },
        ),
    ]
