# Generated by Django 4.0.3 on 2022-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaVentas', '0009_alter_productos_lpa_alter_productos_lpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientoclientes',
            name='Colonia1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='mantenimientoclientes',
            name='DescuentoGeneral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento General (%)'),
        ),
        migrations.AlterField(
            model_name='mantenimientoprospectos',
            name='DescuentoGeneral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento General (%)'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='DescuentoGeneral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento General (%)'),
        ),
    ]
