# Generated by Django 4.0.3 on 2022-05-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaVentas', '0010_mantenimientoclientes_colonia1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimientoclientes',
            options={'ordering': ['id'], 'verbose_name': 'Mantenimiento de Cliente', 'verbose_name_plural': 'Mantenimiento de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='mantenimientoprospectos',
            options={'ordering': ['id'], 'verbose_name': 'Mantenimiento de Prospecto', 'verbose_name_plural': 'Mantenimiento de Prospectos'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['id'], 'verbose_name': 'Producto'},
        ),
        migrations.AlterModelOptions(
            name='solicitudcredito',
            options={'ordering': ['id'], 'verbose_name': 'Solicitud de Credito'},
        ),
    ]
