# Generated by Django 4.0.3 on 2022-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaVentas', '0011_alter_mantenimientoclientes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientoclientes',
            name='Constancia',
            field=models.FileField(null=True, upload_to='constanciasFiscales/'),
        ),
    ]
