# Generated by Django 4.0.3 on 2022-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaVentas', '0012_mantenimientoclientes_constancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoclientes',
            name='CodigoPostal',
            field=models.IntegerField(null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='mantenimientoclientes',
            name='TelefonoCelular',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Numero Celular'),
        ),
        migrations.AlterField(
            model_name='mantenimientoprospectos',
            name='CodigoPostal',
            field=models.IntegerField(null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='mantenimientoprospectos',
            name='TelefonoCelular',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Numero Celular'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='CodigoPostal',
            field=models.IntegerField(null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='Telefono',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Numero Telefonico'),
        ),
    ]
