# Generated by Django 4.0.3 on 2022-04-25 15:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enigmaControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlvisitas',
            name='usuario',
            field=models.ForeignKey(User, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioVisitas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlvisitas',
            name='fecha',
            field=models.DateField(verbose_name=datetime.datetime(2022, 4, 25, 15, 3, 34, 939107, tzinfo=utc)),
        ),
    ]
