# Generated by Django 4.0.3 on 2022-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0004_alter_controlvisitas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlvisitas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
