# Generated by Django 4.0.3 on 2022-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0005_alter_controlvisitas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlvisitas',
            name='duracionVisita',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='controlvisitas',
            name='fecha',
            field=models.DateField(),
        ),
    ]
