# Generated by Django 4.0.3 on 2022-04-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0006_alter_controlvisitas_duracionvisita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlvisitas',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
