# Generated by Django 4.0.3 on 2022-09-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0010_presupuestomodelo_presupuestotabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestotabla',
            name='cantidad',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='cobranzaObjetivo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='cobranzaRealizada',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='ventasObjetivo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='ventasRealizadas',
            field=models.BigIntegerField(),
        ),
    ]
