# Generated by Django 4.0.3 on 2022-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0011_alter_presupuestotabla_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestomodelo',
            name='periodoPresupuesto',
            field=models.CharField(default='Sin datos', max_length=100),
            preserve_default=False,
        ),
    ]
