# Generated by Django 4.0.3 on 2022-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0012_presupuestomodelo_periodopresupuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuestotabla',
            options={'verbose_name': 'Presupuestos Tabla', 'verbose_name_plural': 'Presupuestos Tabla'},
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='cantidad',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='cobranzaObjetivo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='cobranzaRealizada',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='ventasObjetivo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='ventasRealizadas',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
