# Generated by Django 4.0.3 on 2022-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0013_alter_presupuestotabla_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestotabla',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='periodo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuestotabla',
            name='razonSocial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
