# Generated by Django 4.0.3 on 2022-09-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0014_remove_presupuestotabla_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestomodelo',
            name='mesPresupuesto',
        ),
    ]
