# Generated by Django 4.0.3 on 2022-09-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0017_remove_presupuestotabla_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestotabla',
            name='razonSocial',
        ),
    ]
