# Generated by Django 4.0.3 on 2022-09-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0018_remove_presupuestotabla_razonsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestotabla',
            name='razonSocial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
