# Generated by Django 4.0.3 on 2022-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0020_alter_presupuestotabla_razonsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestotabla',
            name='razonSocial',
            field=models.CharField(max_length=100),
        ),
    ]
