# Generated by Django 4.0.3 on 2022-09-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enigmaControl', '0027_alter_presupuestotabla_razonsocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestotabla',
            name='periodo',
        ),
    ]
